src/Application/Rsp.IrasPortal.Application/ServiceClients/IUserManagementServiceClient.cs
Quick fix to set the default page size for Users and Roles Page
- Set the page size to 100 for Users and Roles page
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HealthResearchAuthority/rsp-iras-portal/3)
=> FIX: Set Default Page Size

README.md, azure-pipelines.yaml
- [] Bug-fix
- [] DevOps
- [] Testing
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/HealthResearchAuthority/rsp-iras-portal/5)
=> Updating devops_library_branch reference to GitHub

src/Application/Rsp.IrasPortal.Application/Services/IUserManagementService.cs, src/Services/Rsp.IrasPortal.Services/UserManagementService.cs, src/Web/Rsp.IrasPortal.Web/Areas/Admin/Controllers/RolesController.cs, src/Web/Rsp.IrasPortal.Web/Areas/Admin/Controllers/UsersController.cs, src/Web/Rsp.IrasPortal.Web/Areas/Admin/Models/RoleViewModel.cs, src/Web/Rsp.IrasPortal.Web/Areas/Admin/Views/Roles/Index.cshtml, src/Web/Rsp.IrasPortal.Web/Areas/Admin/Views/Shared/_pagination.cshtml, src/Web/Rsp.IrasPortal.Web/Areas/Admin/Views/Users/Index.cshtml
To provide pagination functionality to the Users & Roles section within the admin functionality.
[RSP-2736](https://nihr.atlassian.net/browse/RSP-2736)
- [] DevOps
- [] Testing
- [  ] Your code builds clean without any  warnings
- [  ] You have added unit tests
- [  ] All the added unit tests add value i.e. assert the right thing?
- [  ] You have fixed all the suggestions made by .editorconfig and/or Roslynator
=> RSP-2736: Implement Pagination on Users and Roles Pages

src/Application/Rsp.IrasPortal.Application/Constants/TempDataKeys.cs, src/Application/Rsp.IrasPortal.Application/DTOs/NavigationDto.cs, src/Application/Rsp.IrasPortal.Application/DTOs/QuestionSectionsResponse.cs, src/Application/Rsp.IrasPortal.Application/ServiceClients/IQuestionSetServiceClient.cs, src/Application/Rsp.IrasPortal.Application/Services/IQuestionSetService.cs, src/Services/Rsp.IrasPortal.Services/QuestionSetService.cs, src/Startup/Rsp.IrasPortal/wwwroot/js/questionnaire.js, src/Startup/Rsp.IrasPortal/wwwroot/js/rules.js, src/Web/Rsp.IrasPortal.Web/Controllers/ApplicationController.cs, src/Web/Rsp.IrasPortal.Web/Controllers/QuestionnaireController.cs, src/Web/Rsp.IrasPortal.Web/Models/ApplicationsViewModel.cs, src/Web/Rsp.IrasPortal.Web/Models/QuestionViewModel.cs, src/Web/Rsp.IrasPortal.Web/Models/QuestionnaireViewModel.cs, src/Web/Rsp.IrasPortal.Web/Views/Application/MyApplications.cshtml, src/Web/Rsp.IrasPortal.Web/Views/Questionnaire/Index.cshtml, src/Web/Rsp.IrasPortal.Web/Views/Shared/_Layout.cshtml, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Controllers/ApplicationControllerTests/MyApplicationsTests.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Controllers/QuestionnaireControllerTests/DisplayQuestionnaireTests.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Controllers/QuestionnaireControllerTests/ResumeTests.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Controllers/QuestionnaireControllerTests/SaveResponsesTests.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Controllers/QuestionnaireControllerTests/ValidateTests.cs
Implement the changes to the section / category API to the UI so we only display one section at a time as part of the question set.
[RSP-2795](https://nihr.atlassian.net/browse/RSP-2795)
- [] Bug-fix
- [] DevOps
- [] Testing
- Implement the API changes to get the previous/current/next section to work out the current flow of the ticket.
- Implement the lookup list component
- Implement the date component
=> RSP-2795 Dynamically show questions by category / section

src/Web/Rsp.IrasPortal.Web/Controllers/ReviewBodyController.cs
Added policy to ensure user logged in when creating a review body.
[RSP-3074 ](https://nihr.atlassian.net/browse/RSP-3074 )
- [] DevOps
- [] Testing
=> RSP-3074 Added authorize policy back to ensure users logged in

src/Application/Rsp.IrasPortal.Application/Configuration/AppSettings.cs, src/Application/Rsp.IrasPortal.Application/Configuration/OneLoginConfiguration.cs, src/Application/Rsp.IrasPortal.Application/Constants/AuthSchemes.cs, src/Application/Rsp.IrasPortal.Application/Constants/ContextItemKeys.cs, src/Application/Rsp.IrasPortal.Application/Constants/Features.cs, src/Infrastructure/Rsp.IrasPortal.Infrastructure/Claims/CustomClaimsTransformation.cs, src/Infrastructure/Rsp.IrasPortal.Infrastructure/HttpMessageHandlers/AuthHeadersHandler.cs, src/Infrastructure/Rsp.IrasPortal.Infrastructure/Rsp.IrasPortal.Infrastructure.csproj, src/Startup/Rsp.IrasPortal/Configuration/Auth/AuthConfiguration.cs, src/Startup/Rsp.IrasPortal/Program.cs, src/Startup/Rsp.IrasPortal/Rsp.IrasPortal.csproj, src/Startup/Rsp.IrasPortal/appsettings.json, src/Startup/Rsp.IrasPortal/featuresettings.json, src/Web/Rsp.IrasPortal.Web/Controllers/AccessTokenController.cs, src/Web/Rsp.IrasPortal.Web/Controllers/AuthController.cs, tests/IntegrationTests/Rsp.IrasPortal.IntegrationTests/5.Infrastructure/AuthHeadersHandlerTests/SendAsyncTests.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Infrastructure/CustomClaimsTransformationTests/UpdateAccessTokenTests.cs
To integrate Gov UK One Login for authentication
[RSP-2796](https://nihr.atlassian.net/browse/RSP-2796)
- Added support for signing in via GovUK One Login using OpenIdConnect.
- Utlised private RSA Key for auth code exchange as GovUK One Logic uses private_jwt_key for authentication
- Added the configuration for Gov UK One Login.
- Utilised feature flag to toggle between IDG and Gov UK One Login
=> RSP-2796: Spike: Integrate with Gov UK Login

src/Web/Rsp.IrasPortal.Web/Views/Questionnaire/Index.cshtml
Fixing create project record issues
[RSP-2988](https://nihr.atlassian.net/browse/RSP-2988)
[RSP-2991](https://nihr.atlassian.net/browse/RSP-2991)
[RSP-2997](https://nihr.atlassian.net/browse/RSP-2997)
[RSP-3002](https://nihr.atlassian.net/browse/RSP-3002)
[RSP-3008](https://nihr.atlassian.net/browse/RSP-3008)
- [] DevOps
- [] Testing
- Updated Questionnaire.Index.cshtml to address cosmetic issues
- Updated Question Set excel record
=> Fixing create project record issues

src/Application/Rsp.IrasPortal.Application/DTOs/Responses/ReviewBodyAuditTrailDto.cs, src/Application/Rsp.IrasPortal.Application/DTOs/Responses/ReviewBodyAuditTrailResponse.cs, src/Application/Rsp.IrasPortal.Application/ServiceClients/IReviewBodyServiceClient.cs, src/Application/Rsp.IrasPortal.Application/Services/IReviewBodyService.cs, src/Infrastructure/Rsp.IrasPortal.Infrastructure/Claims/CustomClaimsTransformation.cs, src/Services/Rsp.IrasPortal.Services/ReviewBodyService.cs, src/Web/Rsp.IrasPortal.Web/Areas/Admin/Models/PaginationViewModel.cs, src/Web/Rsp.IrasPortal.Web/Areas/Admin/Views/Users/EditUserView.cshtml, src/Web/Rsp.IrasPortal.Web/Controllers/ReviewBodyController.cs, src/Web/Rsp.IrasPortal.Web/Models/ReviewBodyAuditTrailViewModel.cs, src/Web/Rsp.IrasPortal.Web/Views/ReviewBody/AuditTrail.cshtml, src/Web/Rsp.IrasPortal.Web/Views/ReviewBody/CreateReviewBody.cshtml, src/Web/Rsp.IrasPortal.Web/Views/Shared/_ReviewBodySummaryTablePartial.cshtml, src/Web/Rsp.IrasPortal.Web/Views/Shared/_pagination.cshtml, tests/UnitTests/Rsp.IrasPortal.UnitTests/Services/ReviewBodyServiceTests/GetReviewBodyAuditTrail.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Controllers/ReviewBodyControllerTests/AuditTrailTestsTests.cs
To review body audit trail functionality
[RSP-2927](https://nihr.atlassian.net/browse/RSP-2927)
=> RSP-2927: View audit history for review body

src/Application/Rsp.IrasPortal.Application/ServiceClients/IReviewBodyServiceClient.cs, src/Application/Rsp.IrasPortal.Application/Services/IReviewBodyService.cs, src/Services/Rsp.IrasPortal.Services/ReviewBodyService.cs, src/Web/Rsp.IrasPortal.Web/Controllers/ReviewBodyController.cs, src/Web/Rsp.IrasPortal.Web/Views/ReviewBody/ReviewBodyStatusChanges.cshtml, src/Web/Rsp.IrasPortal.Web/Views/ReviewBody/SuccessMessage.cshtml, src/Web/Rsp.IrasPortal.Web/Views/ReviewBody/ViewReviewBody.cshtml, tests/UnitTests/Rsp.IrasPortal.UnitTests/Services/ReviewBodyServiceTests/DisableReviewBodyTests.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Services/ReviewBodyServiceTests/EnableReviewBodyTests.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Services/ReviewBodyServiceTests/UpdateReviewBodyTests.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Controllers/ReviewBodyControllerTests/ConfirmStatusUpdateTests.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Controllers/ReviewBodyControllerTests/EnableReviewBodyTests.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Controllers/ReviewBodyControllerTests/ReviewBodyStatusChangesTests.cs
Ability to enable a previously disabled review body
[RSP-2929 (https://nihr.atlassian.net/browse/RSP-2929 )
- [] Bug-fix
- [] DevOps
- [] Testing
=> RSP-2929 enable disabled review body

src/Application/Rsp.IrasPortal.Application/DTOs/Responses/ReviewBodyAuditTrailResponse.cs, src/Application/Rsp.IrasPortal.Application/DTOs/Responses/UserAuditTrailDto.cs, src/Application/Rsp.IrasPortal.Application/DTOs/Responses/UserAuditTrailResponse.cs, src/Application/Rsp.IrasPortal.Application/ServiceClients/IUserManagementServiceClient.cs, src/Application/Rsp.IrasPortal.Application/Services/IUserManagementService.cs, src/Services/Rsp.IrasPortal.Services/UserManagementService.cs, src/Web/Rsp.IrasPortal.Web/Areas/Admin/Controllers/UsersController.cs, src/Web/Rsp.IrasPortal.Web/Areas/Admin/Models/UserAuditTrailViewModel.cs, src/Web/Rsp.IrasPortal.Web/Areas/Admin/Views/Users/UserAuditTrail.cshtml, src/Web/Rsp.IrasPortal.Web/Controllers/ReviewBodyController.cs, src/Web/Rsp.IrasPortal.Web/Views/Shared/_UserSummaryTablePartial.cshtml, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Controllers/ReviewBodyControllerTests/EditNewReviewBodyTests.cs
- [] Bug-fix
- [] DevOps
- [] Testing
=> RSP-2928: Manage users audit log

src/Web/Rsp.IrasPortal.Web/Views/Shared/_ReviewBodySummaryTablePartial.cshtml
[RSP-3127](https://nihr.atlassian.net/browse/RSP-3127)
=> Fix: Review body 'Change' button route

src/Web/Rsp.IrasPortal.Web/Views/SystemAdmin/Index.cshtml
[RSP-3118](https://nihr.atlassian.net/browse/RSP-3118)
- [] DevOps
- [] Testing
- Removed Actions from System Admin page.
- [X ] Your code builds clean without any  warnings
=> RSP-3118 Removed actions header

src/Web/Rsp.IrasPortal.Web/Controllers/ReviewBodyController.cs, src/Web/Rsp.IrasPortal.Web/Views/ReviewBody/SuccessMessage.cshtml
[RSP-3147](https://nihr.atlassian.net/browse/RSP-3147)
[RSP-3159](https://nihr.atlassian.net/browse/RSP-3159)
- [] DevOps
- [] Testing
=> RSP-3147 & RSP 3159 Bug Fixes

src/Web/Rsp.IrasPortal.Web/Views/ReviewBody/ConfirmChanges.cshtml
[RSP-3147](https://nihr.atlassian.net/browse/RSP-3147)
- [] DevOps
- [] Testing
=> RSP-3147 Missing Full Stop

src/Web/Rsp.IrasPortal.Web/Views/ReviewBody/ConfirmChanges.cshtml
[RSP-3178](https://nihr.atlassian.net/browse/RSP-3178)
- [] DevOps
- [] Testing
=> RSP-3178 Add a new review body font size incorrect

src/Web/Rsp.IrasPortal.Web/Views/ReviewBody/ReviewBodyStatusChanges.cshtml, src/Web/Rsp.IrasPortal.Web/Views/Shared/_UserSummaryTablePartial.cshtml
[RSP-3126](https://nihr.atlassian.net/browse/RSP-3127)
[RSP-3137](https://nihr.atlassian.net/browse/RSP-3137)
=> RSP-3126/3137: Bugfixes

src/Web/Rsp.IrasPortal.Web/Areas/Admin/Views/Users/Index.cshtml
- make status tags uniform
Adjust the table heading font size on the manage users page
[RSP-3146](https://nihr.atlassian.net/browse/RSP-3146)
=> RSP-3146: User table font size

src/Application/Rsp.IrasPortal.Application/Constants/UserClaimTypes.cs, src/Application/Rsp.IrasPortal.Application/DTOs/Requests/UserManagement/UserClaimsRequest.cs, src/Application/Rsp.IrasPortal.Application/DTOs/Responses/UserClaimDto.cs, src/Application/Rsp.IrasPortal.Application/DTOs/UserResponse.cs, src/Application/Rsp.IrasPortal.Application/ServiceClients/IUserManagementServiceClient.cs, src/Application/Rsp.IrasPortal.Application/Services/IUserManagementService.cs, src/Services/Rsp.IrasPortal.Services/UserManagementService.cs, src/Web/Rsp.IrasPortal.Web/Areas/Admin/Controllers/UsersController.cs, src/Web/Rsp.IrasPortal.Web/Areas/Admin/Models/UserRoleViewModel.cs, src/Web/Rsp.IrasPortal.Web/Areas/Admin/Models/UserViewModel.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Services/UserManagementServiceTests/UpdateUserAccessTests.cs
handle user access claims
[RSP-3262](https://nihr.atlassian.net/browse/RSP-3262)
[RSP-3263](https://nihr.atlassian.net/browse/RSP-3263)
=> RSP-3262: Handle user access claims

src/Web/Rsp.IrasPortal.Web/Views/Shared/_Layout.cshtml
Re-add navbar item
- [] Bug-fix
- [] DevOps
- [] Testing
=> Re-add 'System admin' navbar item

src/Web/Rsp.IrasPortal.Web/Views/Shared/_pagination.cshtml
- tweak pagination view model
[RSP-3521](https://nihr.atlassian.net/browse/RSP-3521)
=> RSP-3521: Manage users pagination

src/Web/Rsp.IrasPortal.Web/Models/AddUpdateReviewBodyModel.cs, src/Web/Rsp.IrasPortal.Web/Rsp.IrasPortal.Web.csproj, src/Web/Rsp.IrasPortal.Web/Views/ReviewBody/CreateReviewBody.cshtml, src/Web/Rsp.IrasPortal.Web/_ViewImports.cshtml, tests/IntegrationTests/Rsp.IrasPortal.IntegrationTests/Rsp.IrasPortal.IntegrationTests.csproj
Update Create/Edit Review Body to use component library
[RSP-3533](https://nihr.atlassian.net/browse/RSP-3533)
- [] Bug-fix
- [] DevOps
- [] Testing
=> RSP-3533 Updated Create/Edit Review Body to use component library

src/Web/Rsp.IrasPortal.Web/Models/AddUpdateReviewBodyModel.cs, src/Web/Rsp.IrasPortal.Web/Views/ReviewBody/CreateReviewBody.cshtml
[RSP-3730](https://nihr.atlassian.net/browse/RSP-3730 )
- [] DevOps
- [] Testing
=> RSP-3730 Update country to use checbox component

src/Web/Rsp.IrasPortal.Web/Areas/Admin/Views/Users/Index.cshtml, src/Web/Rsp.IrasPortal.Web/Views/ReviewBody/ViewReviewBodies.cshtml
- fix search endpoints
[RSP-3459](https://nihr.atlassian.net/browse/RSP-3459)
=> RSP-3459: search review bodies

src/Web/Rsp.IrasPortal.Web/Rsp.IrasPortal.Web.csproj
Remove Duplicate Ids
[RSP-3817](https://nihr.atlassian.net/browse/RSP-3817)
- [] DevOps
- [] Testing
=> RSP-3817 Remove Duplicate Ids

src/Web/Rsp.IrasPortal.Web/Views/ReviewBody/SuccessAddRemoveUserMessageView.cshtml
Typo fix on the remove user from review body success screen
[RSP-3506](https://nihr.atlassian.net/browse/RSP-3506)
- [] DevOps
- [] Testing
=> RSP-3506: Fix typo

src/Application/Rsp.IrasPortal.Application/DTOs/Requests/UserManagement/CreateUserRequest.cs
Persist lower case user status for create/update requests
[RSP-3818](https://nihr.atlassian.net/browse/RSP-3818)
=> RSP-3818: Persist lower case user status for create/update requests

src/Application/Rsp.IrasPortal.Application/DTOs/ReviewBodyDto.cs, src/Web/Rsp.IrasPortal.Web/Models/AddUpdateReviewBodyModel.cs, src/Web/Rsp.IrasPortal.Web/Views/Shared/_ReviewBodySummaryTablePartial.cshtml
Make LastUpdated nullable and null on creation of new review bodies
[RSP-3125](https://nihr.atlassian.net/browse/RSP-3125)
- [] DevOps
- [] Testing
=> RSP-3125: Remove last updated value for new review bodies

src/Web/Rsp.IrasPortal.Web/Areas/Admin/Views/Users/CreateUserSuccessMessage.cshtml
Remove span tag from success screen
N/A
=> Remove span tag from success screen

src/Web/Rsp.IrasPortal.Web/Areas/Admin/Views/Users/EditUserView.cshtml, src/Web/Rsp.IrasPortal.Web/Rsp.IrasPortal.Web.csproj, src/Web/Rsp.IrasPortal.Web/Views/Questionnaire/EditorTemplates/CheckboxTemplate.cshtml, src/Web/Rsp.IrasPortal.Web/Views/Questionnaire/EditorTemplates/DateTemplate.cshtml, src/Web/Rsp.IrasPortal.Web/Views/Questionnaire/EditorTemplates/RadioButtonTemplate.cshtml, src/Web/Rsp.IrasPortal.Web/Views/Questionnaire/EditorTemplates/TextTemplate.cshtml, src/Web/Rsp.IrasPortal.Web/Views/ReviewBody/CreateReviewBody.cshtml
Update Question Set form to use reusable component library
[RSP-3535](https://nihr.atlassian.net/browse/RSP-3535)
- [] Bug-fix
- [] DevOps
- [] Testing
=> RSP-3535 Update Question Set form to use reusable component library

src/Application/Rsp.IrasPortal.Application/Constants/TempDataKeys.cs, src/Web/Rsp.IrasPortal.Web/Controllers/ApplicationController.cs, src/Web/Rsp.IrasPortal.Web/Controllers/QuestionnaireController.cs, src/Web/Rsp.IrasPortal.Web/Models/QuestionnaireViewModel.cs, src/Web/Rsp.IrasPortal.Web/Rsp.IrasPortal.Web.csproj, src/Web/Rsp.IrasPortal.Web/Views/Application/StartProject.cshtml, src/Web/Rsp.IrasPortal.Web/Views/Questionnaire/EditorTemplates/DateTemplate.cshtml, src/Web/Rsp.IrasPortal.Web/Views/Questionnaire/Index.cshtml, src/Web/Rsp.IrasPortal.Web/Views/Questionnaire/ReviewAnswers.cshtml, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Controllers/QuestionnaireControllerTests/SaveResponsesTests.cs
Implementing back navigation feature and fixing bugs
[RSP-1865](https://nihr.atlassian.net/browse/RSP-1865)
[RSP-1862](https://nihr.atlassian.net/browse/RSP-1862)
[RSP-3867](https://nihr.atlassian.net/browse/RSP-3867)
[RSP-3798](https://nihr.atlassian.net/browse/RSP-3798)
[RSP-3807](https://nihr.atlassian.net/browse/RSP-3807)
- [] DevOps
- [] Testing
=> Implementing back navigation feature and fixing bugs

src/Startup/Rsp.IrasPortal/wwwroot/js/accessible-autocomplete-wrapper.js, src/Web/Rsp.IrasPortal.Web/Rsp.IrasPortal.Web.csproj, src/Web/Rsp.IrasPortal.Web/Views/Questionnaire/EditorTemplates/AutoSuggestTemplate.cshtml, src/Web/Rsp.IrasPortal.Web/Views/Questionnaire/EditorTemplates/TextTemplate.cshtml
RSP-3536 Updated component version for no javascript issues
[RSP-3536](https://nihr.atlassian.net/browse/RSP-3536)
- [] DevOps
- [] Testing
=> RSP-3536 Updated component version for no javascript issues

src/Web/Rsp.IrasPortal.Web/Rsp.IrasPortal.Web.csproj
Added id to checkboxes
[RSP-3898](https://nihr.atlassian.net/browse/RSP-3898)
- [] DevOps
- [] Testing
=> RSP-3898 Added id to checkboxes

src/Web/Rsp.IrasPortal.Web/Views/ReviewBody/CreateReviewBody.cshtml
Change field name for description.
Change field name for description.
[RSP-3887](https://nihr.atlassian.net/browse/RSP-3887)
- [] Bug-fix
- [] DevOps
- [] Testing
- Change the field name.
=> RSP-3887 Changed Description field

src/Web/Rsp.IrasPortal.Web/Controllers/QuestionnaireController.cs, src/Web/Rsp.IrasPortal.Web/Rsp.IrasPortal.Web.csproj
[RSP-4008](https://nihr.atlassian.net/browse/RSP-4008)
- [] DevOps
- [] Testing
=> Date field model data for incorrect entry

src/Application/Rsp.IrasPortal.Application/Constants/TempDataKeys.cs, src/Startup/Rsp.IrasPortal/Program.cs, src/Web/Rsp.IrasPortal.Web/Attributes/ModelStateMergeAttribute.cs, src/Web/Rsp.IrasPortal.Web/Controllers/QuestionnaireController.cs, src/Web/Rsp.IrasPortal.Web/Extensions/ModelStateExtensions.cs, src/Web/Rsp.IrasPortal.Web/Models/OrganisationSearchViewModel.cs, src/Web/Rsp.IrasPortal.Web/Models/QuestionnaireViewModel.cs, src/Web/Rsp.IrasPortal.Web/Views/Questionnaire/EditorTemplates/AutoSuggestTemplate.cshtml, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Controllers/QuestionnaireControllerTests/SaveResponsesTests.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Controllers/QuestionnaireControllerTests/SearchOrganisationsTests.cs
To make the user journey stable when updating the sponsor org from Review Answers page. 
Updated the search button to use secondary button style
[RSP-4017](https://nihr.atlassian.net/browse/RSP-4017)
[RSP-4018](https://nihr.atlassian.net/browse/RSP-4018)
- Added a new attribute `ModelStateMergeAttribute` to merge model state errors.
- Introduced `ModelStateExtensions` to handle merging of model states.
- Updated SearchOrganisations action to redirect to the url so that flow continues from/to the ReviewPage and other pages.
=> RSP-4017, RSP-4018: Sponsor Organisation Update Flow from ReviewPage

src/Web/Rsp.IrasPortal.Web/Views/Questionnaire/Index.cshtml
After landing in questionnaire section from review your answers page, the back navigation was failing.
- [] DevOps
- [] Testing
=> Fixed back navigation error

src/Startup/Rsp.IrasPortal/wwwroot/js/manageUsers.js, src/Web/Rsp.IrasPortal.Web/Areas/Admin/Controllers/UsersController.cs, src/Web/Rsp.IrasPortal.Web/Areas/Admin/Models/UserRoleViewModel.cs, src/Web/Rsp.IrasPortal.Web/Areas/Admin/Models/UserViewModel.cs, src/Web/Rsp.IrasPortal.Web/Areas/Admin/Views/Users/EditUserView.cshtml, src/Web/Rsp.IrasPortal.Web/Extensions/StringExtensions.cs, src/Web/Rsp.IrasPortal.Web/Views/ReviewBody/ConfirmAddRemoveUser.cshtml, src/Web/Rsp.IrasPortal.Web/Views/Shared/_UserSummaryTablePartial.cshtml, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Extensions/TempDataExtensionsTests/SentenceCaseTest.cs
Update date format
[RSP-4026](https://nihr.atlassian.net/browse/RSP-4026)
=> RSP-4026: Update date format

src/Web/Rsp.IrasPortal.Web/Controllers/ApprovalsController.cs, src/Web/Rsp.IrasPortal.Web/Views/Shared/_Layout.cshtml
Add [GOVUK skip link](https://design-system.service.gov.uk/components/skip-link/) across the site
[RSP-3869](https://nihr.atlassian.net/browse/RSP-3869)
- [] DevOps
- [] Testing
=> RSP-3869: Add skip to main content link

src/Web/Rsp.IrasPortal.Web/Views/Approvals/Search.cshtml
Show error message when modification search returns no results
- [] DevOps
- [] Testing
=> fix: Modification search error message

src/Web/Rsp.IrasPortal.Web/Areas/Admin/Views/Users/Index.cshtml
=> RSP-3556 Rebase renamed controller

src/Web/Rsp.IrasPortal.Web/Views/Approvals/Search.cshtml
Modification filter section short project title label text typo fix
- [] DevOps
- [] Testing
=> fix: Modification label text typo

src/Web/Rsp.IrasPortal.Web/Views/Approvals/Search.cshtml
Fix page title on Approvals search page
[RSP-4257](https://nihr.atlassian.net/browse/RSP-4257)
- [] DevOps
- [] Testing
=> RSP-4257: Fix page title

src/Web/Rsp.IrasPortal.Web/Areas/Admin/Views/Users/Index.cshtml, src/Web/Rsp.IrasPortal.Web/Controllers/ApprovalsController.cs, src/Web/Rsp.IrasPortal.Web/Views/Approvals/Search.cshtml, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Controllers/ApprovalsControllerTests/ClearFiltersTests.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Controllers/ApprovalsControllerTests/RemoveFilterTests.cs
Updates to clear filters and remove filters
[RSP-4169](https://nihr.atlassian.net/browse/RSP-4169)
- [] DevOps
- [] Testing
=> RSP-4169 Updates to clear filters and remove filters

src/Web/Rsp.IrasPortal.Web/Views/Shared/_UserSummaryTablePartial.cshtml
Add change link for new users
[RSP-4239](https://nihr.atlassian.net/browse/RSP-4239)
=> RSP-4239: Add change link for new users

src/Web/Rsp.IrasPortal.Web/Views/ReviewBody/ViewReviewBodies.cshtml
Manage review bodies - Advance Filters - UI Labels
[RSP-4299](https://nihr.atlassian.net/browse/RSP-4299)
- [] DevOps
- [] Testing
=> RSP-4299 Manage review bodies - Advance Filters - UI Labels

src/Web/Rsp.IrasPortal.Web/Extensions/ControllerExtensions.cs
- [] Bug-fix
- [] DevOps
- [] Testing
=> - removed NotFound status code to show generic error page

src/Web/Rsp.IrasPortal.Web/Views/Approvals/Search.cshtml
JavaScript Disabled - Approvals - Search - Advanced filter - Sponsor search button behaviour
[RSP-4240](https://nihr.atlassian.net/browse/RSP-4240)
- [] DevOps
- [] Testing
=> RSP-4240 JavaScript Disabled - Approvals - Search - Advanced filter - Sponsor search button behaviour

src/Web/Rsp.IrasPortal.Web/Areas/Admin/Views/Users/Index.cshtml, src/Web/Rsp.IrasPortal.Web/Views/ReviewBody/ViewReviewBodies.cshtml
Update the UI for advanced filters and search on the manage users and manage review bodies pages
[RSP-4273](https://nihr.atlassian.net/browse/RSP-4273)
- [] Bug-fix
- [] DevOps
- [] Testing
=> RSP-4273 Update the UI for advanced filters and search on the manage users and manage review bodies pages

src/Application/Rsp.IrasPortal.Application/Constants/ModificationsTasklist.cs, src/Web/Rsp.IrasPortal.Web/Controllers/ModificationsTasklistController.cs, src/Web/Rsp.IrasPortal.Web/Views/ModificationsTasklist/Index.cshtml, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Controllers/ModificationsTasklistControllerTests/AssignModificationsTests.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Controllers/ModificationsTasklistControllerTests/IndexTests.cs
Provide a brief description of the ticket:
Develop error states (no mod selected and no modifications available to select) for assignment modifications
[RSP-4111](https://nihr.atlassian.net/browse/RSP-4111)
- [] Bug-fix
- [] DevOps
- [] Testing
- List out changes made to the repo:
- Added check for EmptySearchPerformed in ModificationsTasklistController
- Implemented validation of empty list of selected modifications passed to AssignModifications
- Updated modification taskslist view
- Added unit tests
=> Rsp 4111 develop error states for assignment modifications

src/Application/Rsp.IrasPortal.Application/Constants/ModificationOptions.cs, src/Web/Rsp.IrasPortal.Web/Models/ApprovalsSearchModel.cs, src/Web/Rsp.IrasPortal.Web/Validators/ApprovalsSearchModelValidator.cs, src/Web/Rsp.IrasPortal.Web/Views/Approvals/Search.cshtml, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Validators/ApprovalsSearchModelValidatorTests/ValidateAsyncTests.cs
Update the UI for advanced filters
[RSP-4167](https://nihr.atlassian.net/browse/RSP-4167)
- [] Bug-fix
- [] DevOps
- [] Testing
=> RSP-4167 Update the UI for advanced filters & additional validation

src/Startup/Rsp.IrasPortal/featuresettings.json, src/Web/Rsp.IrasPortal.Web/Views/ModificationsTasklist/Index.cshtml
Accessibility - Mod Tasklist - Form elements must have labels
[RSP-4260](https://nihr.atlassian.net/browse/RSP-4260)
- [] DevOps
- [] Testing
=> RSP-4260 Accessibility - Mod Tasklist - Form elements must have labels

src/Application/Rsp.IrasPortal.Application/Constants/QuestionIds.cs, src/Application/Rsp.IrasPortal.Application/Constants/TempDataKeys.cs, src/Application/Rsp.IrasPortal.Application/Constants/ValidationKeys.cs, src/Application/Rsp.IrasPortal.Application/ServiceClients/IApplicationsServiceClient.cs, src/Application/Rsp.IrasPortal.Application/Services/IApplicationsService.cs, src/Services/Rsp.IrasPortal.Services/ApplicationsService.cs, src/Web/Rsp.IrasPortal.Web/Controllers/ApplicationController.cs, src/Web/Rsp.IrasPortal.Web/Controllers/ProjectModificationController.cs, src/Web/Rsp.IrasPortal.Web/Controllers/QuestionnaireController.cs, src/Web/Rsp.IrasPortal.Web/Extensions/ControllerExtensions.cs, src/Web/Rsp.IrasPortal.Web/Models/DateViewModel.cs, src/Web/Rsp.IrasPortal.Web/Models/PlannedEndDateViewModel.cs, src/Web/Rsp.IrasPortal.Web/Models/ProjectOverviewModel.cs, src/Web/Rsp.IrasPortal.Web/Models/QuestionnaireViewModel.cs, src/Web/Rsp.IrasPortal.Web/Validators/DateViewModelValidator.cs, src/Web/Rsp.IrasPortal.Web/Views/Application/Index.cshtml, src/Web/Rsp.IrasPortal.Web/Views/ProjectModification/AreaOfChange.cshtml, src/Web/Rsp.IrasPortal.Web/Views/ProjectModification/PlannedEndDate.cshtml, tests/UnitTests/Rsp.IrasPortal.UnitTests/Services/ApplicationsServiceTests/GetApplicationTests.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Controllers/ApplicationControllerTests/GetProjectOverviewTests.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Controllers/ApplicationControllerTests/ProjectOverviewTests.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Controllers/ProjectModifiationControllerTests/SavePlannedEndDateTests.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Controllers/QuestionnaireControllerTests/DisplayQuestionnaireTests.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Controllers/QuestionnaireControllerTests/ResumeTests.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Validators/DateViewModelValidatorTests/ValidateAsyncTests.cs
To support the modification journey for project planned end date.
[RSP-4097](https://nihr.atlassian.net/browse/RSP-4097)
- [] Bug-fix
- [] DevOps
- [] Testing
- Updated application and web components to support planned end date modifications.
- Introduced new constants and validation keys.
- Added new view models and validators for date handling.
- Enhanced service client interfaces and implementations.
- Updated controllers to handle planned end date logic.
- Added unit tests for new functionality and existing features related to planned end date.
- Improved UI views to reflect changes in planned end date handling.
- Refactored existing code for better …
=> RSP-4097: Planned End Date Modification

src/Web/Rsp.IrasPortal.Web/Areas/Admin/Views/Users/Index.cshtml
Implement UI adjustments on the Manage Users page to address label issues
[RSP-4378](https://nihr.atlassian.net/browse/RSP-4378)
- [] DevOps
- [] Testing
=> RSP-4378 Implement UI adjustments on the Manage Users page to address label issues

src/Application/Rsp.IrasPortal.Application/Constants/OrganisationSearch.cs, src/Application/Rsp.IrasPortal.Application/Constants/OrganisationTypes.cs, src/Application/Rsp.IrasPortal.Application/Constants/TempDataKeys.cs, src/Application/Rsp.IrasPortal.Application/DTOs/OrganisationDto.cs, src/Application/Rsp.IrasPortal.Application/ServiceClients/IRtsServiceClient.cs, src/Application/Rsp.IrasPortal.Application/Services/IRtsService.cs, src/Services/Rsp.IrasPortal.Services/RtsService.cs, src/Web/Rsp.IrasPortal.Web/Controllers/ApprovalsController.cs, src/Web/Rsp.IrasPortal.Web/Controllers/OrganisationController.cs, src/Web/Rsp.IrasPortal.Web/Controllers/ProjectModificationController.cs, src/Web/Rsp.IrasPortal.Web/Controllers/QuestionnaireController.cs, src/Web/Rsp.IrasPortal.Web/Models/OrganisationModel.cs, src/Web/Rsp.IrasPortal.Web/Models/OrganisationSearchModel.cs, src/Web/Rsp.IrasPortal.Web/Models/SearchOrganisationViewModel.cs, src/Web/Rsp.IrasPortal.Web/Models/SelectableOrganisationViewModel.cs, src/Web/Rsp.IrasPortal.Web/Models/TaskListOrganisationViewModel.cs, src/Web/Rsp.IrasPortal.Web/Validators/SearchOrganisationViewModelValidator.cs, src/Web/Rsp.IrasPortal.Web/Views/ProjectModification/SearchOrganisation.cshtml, src/Web/Rsp.IrasPortal.Web/Views/Questionnaire/EditorTemplates/AutoSuggestTemplate.cshtml, tests/UnitTests/Rsp.IrasPortal.UnitTests/Services/RtsServiceTests/RtsServiceTests.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Controllers/ApprovalsControllerTests/SearchOrganisationsTests.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Controllers/OrganisationControllerTests/OrganisationControllerTests.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Controllers/ProjectModifiationControllerTests/ParticipatingOrganisationTests.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Controllers/ProjectModifiationControllerTests/SearchOrganisationTests.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Controllers/QuestionnaireControllerTests/SearchOrganisationsTests.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Validators/SearchOrganisationViewModelValidatorTests/ValidateAsyncTests.cs
User wants to search the RTS feed to find organisations, on the modification, Participating organisation area of change - organisation search page. This ticket adds possibility to get all organisations without filtering by name and adds possibility of pagination. Also imlements UI componenets for ProjectModification > SearchOrganisation view as in figma design.
[RSP-4063](https://nihr.atlassian.net/browse/RSP-4063)
- [] Bug-fix
- [] DevOps
- [] Testing
NOTE - RTS Service also changed and its required to pull these changes in order to test this ticket.
- …
=> Rsp 4063 organisation search and view list

src/Web/Rsp.IrasPortal.Web/Areas/Admin/Views/Users/Index.cshtml
Add date and time in the same p tag. Remove trailing zero from time
[RSP-4304](https://nihr.atlassian.net/browse/RSP-4304)
=> RSP-4304: Add date and time in the same p tag. Remove trailing zero from time

src/Web/Rsp.IrasPortal.Web/Controllers/OrganisationController.cs, src/Web/Rsp.IrasPortal.Web/Views/Questionnaire/EditorTemplates/TextTemplate.cshtml
Provide a brief description of the ticket - minor bugs fix - added email input type to email field in questionnaire and default number of 5 items for sponsor organisation search and autocomplete component.
[RSP-2953](https://nihr.atlassian.net/browse/RSP-2953)
[RSP-3082](https://nihr.atlassian.net/browse/RSP-3082)
[RSP-4590](https://nihr.atlassian.net/browse/RSP-4590)
- [] DevOps
- [] Testing
- List out changes made to the repo:
- added email input type to email field in questionnaire 
- default number of 5 items for sponsor organisation search and autocomplete component.
=> Rsp 4590 2953 3082 email validation and search control defects

src/Web/Rsp.IrasPortal.Web/Models/SortableHeaderModel.cs, src/Web/Rsp.IrasPortal.Web/Views/ReviewBody/ViewReviewBodies.cshtml, src/Web/Rsp.IrasPortal.Web/Views/Shared/_SortableHeaderButton.cshtml, src/Web/Rsp.IrasPortal.Web/Views/Shared/_pagination.cshtml
Manage review bodies - Sort does not work with search & filter
[RSP-4491](https://nihr.atlassian.net/browse/RSP-4491)
- [] DevOps
- [] Testing
Added complex search query to the sortable header object so we can grab the filters which have been applied and keep them in place when sorting the table
=> RSP-4491 Manage review bodies - Sort does not work with search & filter

src/Web/Rsp.IrasPortal.Web/Controllers/ApplicationController.cs, src/Web/Rsp.IrasPortal.Web/Views/Shared/Error.cshtml
Display correlation id on error page
- [] Bug-fix
- [] DevOps
- [] Testing
=> Display correlation id on error page

src/Web/Rsp.IrasPortal.Web/Areas/Admin/Controllers/UsersController.cs, src/Web/Rsp.IrasPortal.Web/Areas/Admin/Views/Users/Index.cshtml, src/Web/Rsp.IrasPortal.Web/Views/Approvals/Search.cshtml, src/Web/Rsp.IrasPortal.Web/Views/ModificationsTasklist/Index.cshtml, src/Web/Rsp.IrasPortal.Web/Views/ProjectModification/SearchOrganisation.cshtml, src/Web/Rsp.IrasPortal.Web/Views/ReviewBody/ViewReviewBodies.cshtml
[RSP-4313](https://nihr.atlassian.net/browse/RSP-4313)
[RSP-4363](https://nihr.atlassian.net/browse/RSP-4363)
[RSP-4373](https://nihr.atlassian.net/browse/RSP-4373)
- [] DevOps
- [] Testing
=> RSP-4313 RSP-4363 RSP-4373 Bug Fixes

src/Web/Rsp.IrasPortal.Web/Views/Approvals/Search.cshtml, src/Web/Rsp.IrasPortal.Web/Views/ModificationsTasklist/Index.cshtml, src/Web/Rsp.IrasPortal.Web/Views/ReviewBody/ViewReviewBodies.cshtml
Implement a collapsed state for the Advanced Filters
[RSP-4293](https://nihr.atlassian.net/browse/RSP-4293)
- [] Bug-fix
- [] DevOps
- [] Testing
- Implement a collapsed state for the Advanced Filters
=> RSP-4293 Implement a collapsed state for the Advanced Filters

src/Application/Rsp.IrasPortal.Application/Configuration/AppSettings.cs, src/Application/Rsp.IrasPortal.Application/Constants/Features.cs, src/Startup/Rsp.IrasPortal/Program.cs, src/Startup/Rsp.IrasPortal/featuresettings.json
To support the web application behind the front door by configuring forwarded headers.
[RSP-4641](https://nihr.atlassian.net/browse/RSP-4641)
- [] Bug-fix
- Added ForwardedHeaders configuration to support Front Door.
- Added FeatureFlag for whether to use front door or not.
=> RSP-4641: Add support for Front Door in application configuration

src/Web/Rsp.IrasPortal.Web/Areas/Admin/Views/Users/UserAuditTrail.cshtml, src/Web/Rsp.IrasPortal.Web/Views/ReviewBody/AuditTrail.cshtml, src/Web/Rsp.IrasPortal.Web/Views/ReviewBody/ConfirmAddRemoveUser.cshtml, src/Web/Rsp.IrasPortal.Web/Views/Shared/_ReviewBodySummaryTablePartial.cshtml, src/Web/Rsp.IrasPortal.Web/Views/Shared/_UserSummaryTablePartial.cshtml
Add line break CSS rule to accomodate for very long emails in tables
[RSP-4099](https://nihr.atlassian.net/browse/RSP-4099)
=> RSP-4099: Email display fix

src/Web/Rsp.IrasPortal.Web/Views/Shared/_UserSummaryTablePartial.cshtml
[RSP-4390](https://nihr.atlassian.net/browse/RSP-4390)
- [] DevOps
- [] Testing
=> RSP-4390 Updated Partial Roles for new Roles

src/Application/Rsp.IrasPortal.Application/Configuration/AppSettings.cs, src/Startup/Rsp.IrasPortal/appsettings.json, src/Web/Rsp.IrasPortal.Web/Views/Shared/_Layout.cshtml
Implement Microsoft Clarity
[RSP-4089](https://nihr.atlassian.net/browse/RSP-4089)
- [] Bug-fix
- [] DevOps
- [] Testing
=> RSP-4089: Microsoft Clarity PoC

src/Web/Rsp.IrasPortal.Web/Areas/Admin/Views/Users/Index.cshtml
Manage Users - Advanced Filter - Clear all filters link should not reset the search box
[RSP-4898](https://nihr.atlassian.net/browse/RSP-4898)
- [] DevOps
- [] Testing
=> RSP-4898 Manage Users - Advanced Filter - Clear all filters link should not reset the search box

src/Web/Rsp.IrasPortal.Web/Controllers/ApprovalsController.cs, src/Web/Rsp.IrasPortal.Web/Models/ApprovalsSearchModel.cs, src/Web/Rsp.IrasPortal.Web/Views/Approvals/Search.cshtml
JavaScript Disabled - Approvals - Search - Advanced filter - Sponsor search button clears other filter
[RSP-4467](https://nihr.atlassian.net/browse/RSP-4467)
- [] DevOps
- [] Testing
=> RSP-4467 JavaScript Disabled - Approvals - Search - Advanced filter - Sponsor search button clears other filter

src/Application/Rsp.IrasPortal.Application/Constants/TempDataKeys.cs, src/Application/Rsp.IrasPortal.Application/DTOs/ModificationsDto.cs, src/Application/Rsp.IrasPortal.Application/ServiceClients/IProjectModificationsServiceClient.cs, src/Application/Rsp.IrasPortal.Application/Services/IProjectModificationsService.cs, src/Services/Rsp.IrasPortal.Services/ProjectModificationsService.cs, src/Startup/Rsp.IrasPortal/featuresettings.json, src/Web/Rsp.IrasPortal.Web/Controllers/ModificationsTasklistController.cs, src/Web/Rsp.IrasPortal.Web/Models/ModificationsModel.cs, src/Web/Rsp.IrasPortal.Web/Views/ModificationsTasklist/AssignModifications.cshtml, src/Web/Rsp.IrasPortal.Web/Views/ModificationsTasklist/AssignmentSuccess.cshtml, src/Web/Rsp.IrasPortal.Web/Views/ModificationsTasklist/Index.cshtml, tests/UnitTests/Rsp.IrasPortal.UnitTests/Services/ProjectModificationServiceTests/AssignModificationsToReviewer.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Services/ProjectModificationServiceTests/GetModificationsByIds.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Controllers/ModificationsTasklistControllerTests/AssignModificationsTests.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Controllers/ModificationsTasklistControllerTests/AssignmentSuccessTests.cs
Develop modification assignment flow
[RSP-4076](https://nihr.atlassian.net/browse/RSP-4076)
[RSP-4849](https://nihr.atlassian.net/browse/RSP-4849)
- [] Bug-fix
- [] DevOps
- [] Testing
=> RSP-4076/4849: Develop modification assignment flow

src/Application/Rsp.IrasPortal.Application/DTOs/ReviewBodyUserDto.cs, src/Web/Rsp.IrasPortal.Web/Areas/Admin/Controllers/UsersController.cs, src/Web/Rsp.IrasPortal.Web/Areas/Admin/Views/Users/Index.cshtml, src/Web/Rsp.IrasPortal.Web/Controllers/ReviewBodyController.cs, src/Web/Rsp.IrasPortal.Web/Validators/ApprovalsSearchModelValidator.cs, src/Web/Rsp.IrasPortal.Web/Validators/UserSearchModelValidator.cs, src/Web/Rsp.IrasPortal.Web/Views/ModificationsTasklist/Index.cshtml
UI adjustments:
[RSP-4819](https://nihr.atlassian.net/browse/RSP-4819)
- [] Bug-fix
- [] DevOps
- [] Testing
=> RSP-4819: UI adjustments

src/Web/Rsp.IrasPortal.Web/Views/Shared/LoginLandingPageContent.cshtml
Add additional null checks to LoginLandingPartial
[RSP-4912](https://nihr.atlassian.net/browse/RSP-4912)
=> RSP-4912: Handle static content

src/Startup/Rsp.IrasPortal/featuresettings.json, src/Web/Rsp.IrasPortal.Web/Areas/Admin/Controllers/HomeController.cs, src/Web/Rsp.IrasPortal.Web/Controllers/ModificationsTasklistController.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Controllers/ModificationsTasklistControllerTests/AssignModificationsTests.cs
Fix list of SWRs on Assign modification page not showing correct SWRs
[RSP-5010](https://nihr.atlassian.net/browse/RSP-5010)
- [] DevOps
- [] Testing
=> RSP-5010: Incorrect list of SWRs

src/Application/Rsp.IrasPortal.Application/DTOs/Responses/CmsContent/MixedContentPageResponse.cs, src/Application/Rsp.IrasPortal.Application/Filters/SiteContentFilter.cs, src/Application/Rsp.IrasPortal.Application/ServiceClients/ICmsContentServiceClient.cs, src/Application/Rsp.IrasPortal.Application/Services/ICmsContentService.cs, src/Infrastructure/Rsp.IrasPortal.Infrastructure/HttpMessageHandlers/CmsPreviewHeadersHandler.cs, src/Services/Rsp.IrasPortal.Services/CmsContentService.cs, src/Startup/Rsp.IrasPortal/Configuration/Dependencies/ServicesConfiguration.cs, src/Startup/Rsp.IrasPortal/Configuration/HttpClients/HttpClientsConfiguration.cs, src/Startup/Rsp.IrasPortal/featuresettings.json, src/Web/Rsp.IrasPortal.Web/Controllers/CmsContent/CmsContentController.cs, src/Web/Rsp.IrasPortal.Web/ViewComponents/LoginLandingPageViewComponent.cs, src/Web/Rsp.IrasPortal.Web/Views/Approvals/Index.cshtml, src/Web/Rsp.IrasPortal.Web/Views/ApprovalsMenu/Index.cshtml, src/Web/Rsp.IrasPortal.Web/Views/ModificationsTasklist/Index.cshtml, src/Web/Rsp.IrasPortal.Web/Views/MyTasklist/Index.cshtml, src/Web/Rsp.IrasPortal.Web/Views/ResearchAccount/Index.cshtml, src/Web/Rsp.IrasPortal.Web/Views/Shared/ContentComponents/Tabs.cshtml, src/Web/Rsp.IrasPortal.Web/Views/Shared/_Layout.cshtml, tests/IntegrationTests/Rsp.IrasPortal.IntegrationTests/5.Infrastructure/AuthHeadersHandlerTests/CmsPreviewSendAsyncTests.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Services/CmsContentServiceTests/GeLoginLandingPageContentTests.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Services/CmsContentServiceTests/GetGenericPageContentTests.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Services/CmsContentServiceTests/GetMixedPageContentTests.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Services/CmsContentServiceTests/GetSiteSettingsTests.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Controllers/CmsContentControllerTests/RenderCmsContentTests.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/ViewComponents/LoginLandingViewComponentTests/LoginLandingPageComponentTests.cs
To start retrofit mixed content pages: 
- Approvals menu
- Approvals/mytasklist
- Approvals/modificationstasklist
- Approvals/Search
- [] Bug-fix
- [] DevOps
- [] Testing
=> RSP-4915: start retrofit mixed content pages

src/Startup/Rsp.IrasPortal/appsettings.json, src/Web/Rsp.IrasPortal.Web/Views/MyTasklist/Index.cshtml, src/Web/Rsp.IrasPortal.Web/Views/Shared/ContentComponents/Accordion.cshtml, src/Web/Rsp.IrasPortal.Web/Views/Shared/ContentComponents/RichText.cshtml
Fix search hint label on my tasklist page
=> Fix search hint label on my tasklist page

src/Web/Rsp.IrasPortal.Web/Controllers/QuestionnaireController.cs, src/Web/Rsp.IrasPortal.Web/Views/Questionnaire/ProjectRecordCreated.cshtml, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Controllers/QuestionnaireControllerTests/ConfirmProjectDetaisTests.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Controllers/QuestionnaireControllerTests/ProjectRecordCreatedTests.cs
Add a confirmation screen on project record completion
[RSP-4880](https://nihr.atlassian.net/browse/RSP-4880)
- [] Bug-fix
- [] DevOps
- [] Testing
=> RSP-4880: Project record confirmation screen

src/Application/Rsp.IrasPortal.Application/Constants/ModificationQuestionIds.cs, src/Application/Rsp.IrasPortal.Application/DTOs/ProjectOverviewDocumentDto.cs, src/Application/Rsp.IrasPortal.Application/DTOs/Requests/ProjectOverviewDocumentSearchRequest.cs, src/Application/Rsp.IrasPortal.Application/DTOs/Responses/ProjectOverviewDocumentResponse.cs, src/Application/Rsp.IrasPortal.Application/ServiceClients/IProjectModificationsServiceClient.cs, src/Application/Rsp.IrasPortal.Application/Services/IProjectModificationsService.cs, src/Services/Rsp.IrasPortal.Services/ProjectModificationsService.cs, src/Web/Rsp.IrasPortal.Web/Controllers/ProjectOverview/ProjectOverviewController.cs, src/Web/Rsp.IrasPortal.Web/Features/Modifications/Documents/Controllers/DocumentsController.cs, src/Web/Rsp.IrasPortal.Web/Models/ProjectDocumentsSearchModel.cs, src/Web/Rsp.IrasPortal.Web/Models/ProjectOverviewDocumentViewModel.cs, src/Web/Rsp.IrasPortal.Web/Views/ProjectOverview/ProjectDocuments.cshtml, src/Web/Rsp.IrasPortal.Web/Views/Shared/_SortableHeaderButton.cshtml, tests/UnitTests/Rsp.IrasPortal.UnitTests/Services/ProjectModificationServiceTests/GetDocumentsForProjectOverview.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Controllers/ProjectOverviewControllerTests/ProjectOverviewTests.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Features/Modifications/Documents/AddDocumentDetailsListTests.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Features/Modifications/Documents/ContinueToDetailsTests.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Features/Modifications/Documents/UploadDocumentTests.cs
Implemented project documents tab in project overview
[RSP-4545](https://nihr.atlassian.net/browse/RSP-4545)
- [] Bug-fix
- [] DevOps
- [] Testing
=> Implemented project documents tab in project overview

src/Startup/Rsp.IrasPortal/Configuration/AppConfiguration/AzureAppConfiguration.cs
- [] Bug-fix
- [] DevOps
- [] Testing
=> Integrated KeyVault

src/Web/Rsp.IrasPortal.Web/Views/ModificationsTasklist/Index.cshtml
Swap empty search content placeholder
[RSP-5208](https://nihr.atlassian.net/browse/RSP-5208)
=> RSP-5208: empty search placeholder swap

src/Application/Rsp.IrasPortal.Application/Filters/SiteContentFilter.cs, src/Application/Rsp.IrasPortal.Application/ServiceClients/ICmsContentServiceClient.cs, src/Application/Rsp.IrasPortal.Application/Services/ICmsContentService.cs, src/Services/Rsp.IrasPortal.Services/CmsContentService.cs, src/Web/Rsp.IrasPortal.Web/Controllers/ApplicationController.cs, src/Web/Rsp.IrasPortal.Web/Views/Application/CreateApplication.cshtml, src/Web/Rsp.IrasPortal.Web/Views/Application/Index.cshtml, src/Web/Rsp.IrasPortal.Web/Views/Application/StartProject.cshtml, src/Web/Rsp.IrasPortal.Web/Views/ResearchAccount/Index.cshtml, tests/UnitTests/Rsp.IrasPortal.UnitTests/Services/CmsContentServiceTests/GetDashboardContentTests.cs
Add additional content placeholders
[RSP-5015](https://nihr.atlassian.net/browse/RSP-5015)
=> RSP-5015: Add additional content placeholders

src/Application/Rsp.IrasPortal.Application/Constants/FileConstants.cs, src/Application/Rsp.IrasPortal.Application/DTOs/Requests/ProjectModificationDocumentRequest.cs, src/Application/Rsp.IrasPortal.Application/ServiceClients/IProjectModificationsServiceClient.cs, src/Application/Rsp.IrasPortal.Application/Services/IBlobStorageService.cs, src/Application/Rsp.IrasPortal.Application/Services/IProjectModificationsService.cs, src/Services/Rsp.IrasPortal.Services/BlobStorageService.cs, src/Services/Rsp.IrasPortal.Services/ProjectModificationsService.cs, src/Web/Rsp.IrasPortal.Web/Features/Modifications/Documents/Controllers/DocumentsController.cs, src/Web/Rsp.IrasPortal.Web/Features/Modifications/Documents/Views/AddDocumentDetails.cshtml, src/Web/Rsp.IrasPortal.Web/Features/Modifications/Documents/Views/DeleteDocuments.cshtml, src/Web/Rsp.IrasPortal.Web/Features/Modifications/Documents/Views/ModificationDocumentsAdded.cshtml, src/Web/Rsp.IrasPortal.Web/Features/Modifications/Documents/Views/UploadDocuments.cshtml, src/Web/Rsp.IrasPortal.Web/Models/ModificationDeleteDocumentViewModel.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Services/BlobStorageServiceTests/DeleteFileTests.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Services/ProjectModificationServiceTests/DeleteDocumentModification.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Features/Modifications/Documents/ConfirmDeleteDocumentTests.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Features/Modifications/Documents/ConfirmDeleteDocumentsTests.cs, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Features/Modifications/Documents/DeleteDocumentsTests.cs
Delete project document
[RSP-3888](https://nihr.atlassian.net/browse/RSP-3888)
- [] Bug-fix
- [] DevOps
- [] Testing
=> Delete project document

src/Web/Rsp.IrasPortal.Web/Features/Modifications/ReviewAllChangesController.cs, src/Web/Rsp.IrasPortal.Web/Features/Modifications/Shared/ModificationSentToSponsor.cshtml, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Features/Modifications/ReviewAllChangesControllerTests/SendModificationToSponsor.cs
Submit to regulator
[RSP-4863](https://nihr.atlassian.net/browse/RSP-4863)
- [] Bug-fix
- [] DevOps
- [] Testing
=> Submit to regulator

src/Startup/Rsp.IrasPortal/wwwroot/js/modificationsTasklist.js, src/Web/Rsp.IrasPortal.Web/Controllers/ModificationsTasklistController.cs, src/Web/Rsp.IrasPortal.Web/Views/ModificationsTasklist/AssignModifications.cshtml, src/Web/Rsp.IrasPortal.Web/Views/Shared/_SortableHeaderButton.cshtml, tests/UnitTests/Rsp.IrasPortal.UnitTests/Web/Controllers/ModificationsTasklistControllerTests/IndexTests.cs
[RSP-4976](https://nihr.atlassian.net/browse/RSP-4976)
[RSP-5011](https://nihr.atlassian.net/browse/RSP-5011)
- [] DevOps
- [] Testing
=> RSP-4976 RSP-5011 Bug Fixes
